services:
  listener:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    working_dir: /workspace/WebApplication1
    volumes:
      - ./:/workspace:cached
    networks:
      - devnet
    ports:
      - "5000:5000"
    command: tail -f /dev/null

networks:
  devnet:
    external: true
